const express = require('express');
const cors = require('cors');
const path = require('path');
const { fetch: undiciFetch } = require('undici');
const { YoutubeTranscript } = require('youtube-transcript');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ── Constants ────────────────────────────────────────────────────────

const USER_AGENT =
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// ── Helpers ──────────────────────────────────────────────────────────

function extractVideoId(input) {
    if (!input) return null;
    input = input.trim();
    if (/^[a-zA-Z0-9_-]{11}$/.test(input)) return input;
    try {
        const url = new URL(input);
        const host = url.hostname.replace('www.', '');
        if (host === 'youtu.be') return url.pathname.slice(1).split('/')[0] || null;
        if (host === 'youtube.com' || host === 'm.youtube.com') {
            if (url.searchParams.has('v')) return url.searchParams.get('v');
            const m = url.pathname.match(/^\/(embed|v|shorts|live)\/([a-zA-Z0-9_-]{11})/);
            if (m) return m[2];
        }
    } catch { }
    const fb = input.match(/(?:v=|\/|youtu\.be\/)([a-zA-Z0-9_-]{11})/);
    return fb ? fb[1] : null;
}

// ── API: Video Metadata ──────────────────────────────────────────────

app.get('/api/metadata', async (req, res) => {
    try {
        const videoId = extractVideoId(req.query.url || req.query.videoId || '');
        if (!videoId) {
            return res.status(400).json({ error: 'INVALID_URL', message: 'Please provide a valid YouTube URL.' });
        }

        const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
        const r = await undiciFetch(oembedUrl, {
            headers: { 'User-Agent': USER_AGENT },
            signal: AbortSignal.timeout(10000),
        });
        const data = await r.json();

        res.json({
            videoId,
            title: data.title || 'Unknown Title',
            author: data.author_name || 'Unknown',
            thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
        });
    } catch (err) {
        res.status(404).json({
            error: 'VIDEO_UNAVAILABLE',
            message: 'Video not found. It may be private, removed, or the URL is incorrect.',
        });
    }
});

// ── API: Transcript ──────────────────────────────────────────────────

app.get('/api/transcript', async (req, res) => {
    try {
        const videoId = extractVideoId(req.query.url || req.query.videoId || '');
        if (!videoId) {
            return res.status(400).json({ error: 'INVALID_URL', message: 'Please provide a valid YouTube URL.' });
        }

        const requestedLang = req.query.lang || '';

        // Fetch transcript using youtube-transcript library
        let transcriptResult;
        try {
            // Get available transcripts
            const available = await YoutubeTranscript.fetchTranscript(videoId, { lang: 'en' });

            if (!available || available.length === 0) {
                return res.status(404).json({
                    error: 'NO_TRANSCRIPT',
                    message: 'No captions available for this video.',
                });
            }

            transcriptResult = available;
        } catch (err) {
            if (err.message?.includes('Could not get transcript') || err.message?.includes('not available')) {
                return res.status(404).json({
                    error: 'NO_TRANSCRIPT',
                    message: 'No captions available for this video.',
                });
            }
            if (err.message?.includes('sign in') || err.message?.includes('bot')) {
                return res.status(403).json({
                    error: 'RATE_LIMITED',
                    message: err.message || 'YouTube requires verification. Please try again later.',
                });
            }
            throw err;
        }

        // Convert to our format
        const segments = transcriptResult.map((item) => ({
            text: item.text,
            offset: Math.round(item.offset * 1000),
            duration: Math.round((item.duration || 3) * 1000),
        }));

        // Build language info
        const languages = [{
            code: requestedLang || 'en',
            name: requestedLang || 'English',
            isAutoGenerated: false,
        }];

        res.json({
            videoId,
            language: requestedLang || 'en',
            languageName: requestedLang || 'English',
            isAutoGenerated: false,
            availableLanguages: languages,
            segments,
        });
    } catch (err) {
        console.error('Transcript error:', err.message || err);
        console.error('Full error object:', JSON.stringify(err, null, 2));
        const status =
            err.code === 'RATE_LIMITED' ? 429
                : err.code === 'VIDEO_UNAVAILABLE' ? 404
                    : err.code === 'NO_TRANSCRIPT' ? 404
                        : 500;
        res.status(status).json({
            error: err.code || 'SERVER_ERROR',
            message: err.message || 'An unexpected error occurred while fetching the transcript.',
        });
    }
});

// ── SPA fallback ─────────────────────────────────────────────────────

app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// ── Start ────────────────────────────────────────────────────────────

app.listen(PORT, () => {
    console.log(`✨ YT-Scribe server running at http://localhost:${PORT}`);
});
